import AppKit

/// Polls NSPasteboard.general for changes (there is no push API on macOS)
/// and hands captured content to the store.
final class ClipboardMonitor {
    var onCapture: ((ClipboardContent, NSRunningApplication?) -> Void)?

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    /// Pasteboard types that mark content as not-for-history:
    /// password managers, transient data, auto-generated data.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    func start() {
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
        // .common so capture keeps working while menus/scrolling block the default mode.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.excludedTypes) else { return }

        guard let content = Self.extractContent(from: pasteboard) else { return }
        onCapture?(content, NSWorkspace.shared.frontmostApplication)
    }

    static func extractContent(from pasteboard: NSPasteboard) -> ClipboardContent? {
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return .files(urls)
        }

        let imageData = pngData(from: pasteboard)
        let string = pasteboard.string(forType: .string)?
            .trimmingCharacters(in: .whitespacesAndNewlines)

        if let string, !string.isEmpty {
            // "Copy Image" in browsers often puts the image URL in the text slot;
            // prefer the image in that case, otherwise the text wins (e.g. Excel
            // cells also carry a rendered image of the selection).
            if let imageData, isImageAuxiliaryText(string) {
                return .image(imageData)
            }
            return .text(string)
        }

        if let imageData {
            return .image(imageData)
        }
        return nil
    }

    private static func pngData(from pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) {
            return png
        }
        if let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return png
        }
        return nil
    }

    private static func isImageAuxiliaryText(_ string: String) -> Bool {
        guard !string.contains("\n") else { return false }
        return string.hasPrefix("http://") || string.hasPrefix("https://") || string.hasPrefix("file://")
    }
}
